version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
- package-ecosystem: docker
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
# Check github actions are up to date.
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  assignees:
  - M0NsTeRRR
